[package]
org = "ballroom"
name = "contest_service"
version = "0.1.0"
distribution = "2201.6.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballroom"
name = "data_model"
version = "0.1.0"

[[dependency]]
org = "ballroom"
name = "entities"
version = "0.1.0"
