[package]
distribution = "2201.6.0"
name = "upload_service"
org = "ballroom"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
name = "data_model"
org = "ballroom"
version = "0.1.0"

[[dependency]]
org = "ballroom"
name = "entities"
version = "0.1.0"
